import { LiveDotEvent } from "@/types/event";

const DEFAULT_TECH_CHECK = {
  items: {
    audio_check: false,
    video_check: false,
    latency_check: false,
    backup_stream: false,
    chat_moderation: false,
  },
  signedOffAt: null,
};

export const MOCK_EVENTS: LiveDotEvent[] = [
  {
    id: "evt_001",
    title: "The Future of African Tech",
    description:
      "A deep-dive panel on fintech, infrastructure, and the next wave of African startups shaping the continent.",
    hostName: "Amara Osei",
    scheduledAt: "2026-04-15T18:00:00Z",
    ticketPrice: 15,
    isFree: false,
    attendeeCount: 340,
    state: "scheduled",
    streamIngest: null,
    assignedCrew: [
      { id: "crew_01", name: "Kofi Mensah", role: "Stream Director", avatarInitials: "KM" },
    ],
    techCheck: { ...DEFAULT_TECH_CHECK, items: { ...DEFAULT_TECH_CHECK.items } },
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-10T14:22:00Z",
    requirements: [
      { key: "crew_assigned",      label: "Production crew assigned",       description: "At least one production crew member must be assigned.", completed: true  },
      { key: "ingest_configured",  label: "Streaming ingest configured",    description: "RTMP ingest endpoint must be set up and tested.",        completed: false },
      { key: "pricing_configured", label: "Ticket pricing configured",      description: "Ticket price must be set before the event can go live.", completed: true  },
      // { key: "venue_confirmed",    label: "Venue / stream source confirmed", description: "The stream source or physical venue must be confirmed.", completed: false },
      { key: "tech_check_done",    label: "Tech check completed",           description: "A full technical rehearsal must be signed off.",         completed: false },
    ],
  },
  {
    id: "evt_002",
    title: "Lagos Jazz Sessions — Vol. 3",
    description:
      "Live jazz from some of Lagos' most exciting emerging artists. Intimate. Electric. Unmissable.",
    hostName: "Tunde Fashola",
    scheduledAt: "2026-04-22T20:00:00Z",
    ticketPrice: 8,
    isFree: false,
    attendeeCount: 512,
    state: "ready",
    streamIngest: { sourceType: "rtmp_obs", rtmpUrl: "rtmp://live.livdot.io/stream/evt_002" },
    assignedCrew: [
      { id: "crew_02", name: "Ngozi Adeyemi",  role: "Audio Engineer",     avatarInitials: "NA" },
      { id: "crew_03", name: "Tariq Hassan",   role: "Camera Operator",    avatarInitials: "TH" },
    ],
    techCheck: {
      items: { audio_check: true, video_check: true, latency_check: true, backup_stream: true, chat_moderation: true },
      signedOffAt: "2026-03-09T11:00:00Z",
    },
    createdAt: "2026-02-20T09:00:00Z",
    updatedAt: "2026-03-09T11:00:00Z",
    requirements: [
      { key: "crew_assigned",      label: "Production crew assigned",        description: "At least one production crew member must be assigned.", completed: true },
      { key: "ingest_configured",  label: "Streaming ingest configured",     description: "RTMP ingest endpoint must be set up and tested.",        completed: true },
      { key: "pricing_configured", label: "Ticket pricing configured",       description: "Ticket price must be set before the event can go live.", completed: true },
      // { key: "venue_confirmed",    label: "Venue / stream source confirmed",  description: "The stream source or physical venue must be confirmed.", completed: true },
      { key: "tech_check_done",    label: "Tech check completed",            description: "A full technical rehearsal must be signed off.",         completed: true },
    ],
  },
  {
    id: "evt_003",
    title: "Nairobi Startup Summit 2026",
    description: "East Africa's premier startup event — pitches, workshops, and networking.",
    hostName: "Wanjiru Kamau",
    scheduledAt: null,
    ticketPrice: null,
    isFree: false,
    attendeeCount: 0,
    state: "draft",
    streamIngest: null,
    assignedCrew: [],
    techCheck: { ...DEFAULT_TECH_CHECK, items: { ...DEFAULT_TECH_CHECK.items } },
    createdAt: "2026-03-10T08:30:00Z",
    updatedAt: "2026-03-10T08:30:00Z",
    requirements: [
      { key: "crew_assigned",      label: "Production crew assigned",        description: "At least one production crew member must be assigned.", completed: false },
      { key: "ingest_configured",  label: "Streaming ingest configured",     description: "RTMP ingest endpoint must be set up and tested.",        completed: false },
      { key: "pricing_configured", label: "Ticket pricing configured",       description: "Ticket price must be set before the event can go live.", completed: false },
      // { key: "venue_confirmed",    label: "Venue / stream source confirmed",  description: "The stream source or physical venue must be confirmed.", completed: false },
      { key: "tech_check_done",    label: "Tech check completed",            description: "A full technical rehearsal must be signed off.",         completed: false },
    ],
  },
  {
    id: "evt_004",
    title: "Afrobeats World Tour — Live Stream",
    description: "Catch the full live stream of the Afrobeats World Tour from Lagos. Night one.",
    hostName: "DJ Khalid Eko",
    scheduledAt: "2026-03-11T21:00:00Z",
    ticketPrice: 20,
    isFree: false,
    attendeeCount: 1204,
    state: "live",
    streamIngest: { sourceType: "rtmp_obs", rtmpUrl: "rtmp://live.livdot.io/stream/evt_004" },
    assignedCrew: [
      { id: "crew_05", name: "Emeka Okafor",  role: "Technical Producer", avatarInitials: "EO" },
      { id: "crew_06", name: "Yewande Bello", role: "Chat Moderator",     avatarInitials: "YB" },
    ],
    techCheck: {
      items: { audio_check: true, video_check: true, latency_check: true, backup_stream: true, chat_moderation: true },
      signedOffAt: "2026-03-11T20:00:00Z",
    },
    createdAt: "2026-02-01T12:00:00Z",
    updatedAt: "2026-03-11T21:00:00Z",
    requirements: [
      { key: "crew_assigned",      label: "Production crew assigned",        description: "At least one production crew member must be assigned.", completed: true },
      { key: "ingest_configured",  label: "Streaming ingest configured",     description: "RTMP ingest endpoint must be set up and tested.",        completed: true },
      { key: "pricing_configured", label: "Ticket pricing configured",       description: "Ticket price must be set before the event can go live.", completed: true },
      // { key: "venue_confirmed",    label: "Venue / stream source confirmed",  description: "The stream source or physical venue must be confirmed.", completed: true },
      { key: "tech_check_done",    label: "Tech check completed",            description: "A full technical rehearsal must be signed off.",         completed: true },
    ],
  },
  {
    id: "evt_005",
    title: "Women in Leadership: Africa Edition",
    description: "A powerful conversation with Africa's top female executives and changemakers.",
    hostName: "Fatima Al-Hassan",
    scheduledAt: "2026-02-28T17:00:00Z",
    ticketPrice: 12,
    isFree: false,
    attendeeCount: 890,
    state: "replay",
    streamIngest: { sourceType: "zoom", zoomMeetingId: "812 3456 7890" },
    assignedCrew: [
      { id: "crew_04", name: "Amina Diallo",  role: "Graphics Operator",   avatarInitials: "AD" },
      { id: "crew_07", name: "Seun Adeola",   role: "Replay Editor",       avatarInitials: "SA" },
    ],
    techCheck: {
      items: { audio_check: true, video_check: true, latency_check: true, backup_stream: true, chat_moderation: true },
      signedOffAt: "2026-02-27T16:00:00Z",
    },
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-03-01T09:00:00Z",
    requirements: [
      { key: "crew_assigned",      label: "Production crew assigned",        description: "At least one production crew member must be assigned.", completed: true },
      { key: "ingest_configured",  label: "Streaming ingest configured",     description: "RTMP ingest endpoint must be set up and tested.",        completed: true },
      { key: "pricing_configured", label: "Ticket pricing configured",       description: "Ticket price must be set before the event can go live.", completed: true },
      // { key: "venue_confirmed",    label: "Venue / stream source confirmed",  description: "The stream source or physical venue must be confirmed.", completed: true },
      { key: "tech_check_done",    label: "Tech check completed",            description: "A full technical rehearsal must be signed off.",         completed: true },
    ],
  },
];
